version: "3.9"

services:

  #Nginx (public-facing reverse proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shadowguard
    networks:
      - waf_net
    restart: unless-stopped

  #ShadowGuard ML-WAF
  shadowguard:
    build: .
    expose:
      - "5000"
    volumes:
      - ./models:/app/models:ro
      - ./logs:/app/logs
    environment:
      - TARGET_APP_URL=http://targetapp:8080
      - PYTHONUNBUFFERED=1
    depends_on:
      - targetapp
    networks:
      - waf_net
    restart: unless-stopped
    # Security hardening
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  #Target App (vulnerable, internal only)
  targetapp:
    build:
      context: .
      dockerfile: targetapp.Dockerfile
    working_dir: /app
    expose:
      - "8080"
    networks:
      - waf_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  waf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
